// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Kosov_backend.Data;

#nullable disable

namespace Kosov_backend.Migrations
{
    [DbContext(typeof(Kosov_backendContext))]
    [Migration("20241113124434_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kosov_backend.Models.StateTelegram", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StateTelegram");
                });

            modelBuilder.Entity("Kosov_backend.Models.SubscribeRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<string>("IdTelegram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTimeChunks")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SubscribeRoom");
                });

            modelBuilder.Entity("Kosov_backend.Models.TimeChunk", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TimeChunk");
                });

            modelBuilder.Entity("Kosov_backend.Models.User", b =>
                {
                    b.Property<string>("IdTelegram")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdStateTelegram")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagTelegram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTelegram");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
