// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhuchkov_backend.Data;

#nullable disable

namespace Zhuchkov_backend.Migrations
{
    [DbContext(typeof(Zhuchkov_backendContext))]
    [Migration("20241203172650_visual")]
    partial class visual
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SubscribeRoomTimeChunk", b =>
                {
                    b.Property<int>("SubscribeRoomId")
                        .HasColumnType("int");

                    b.Property<int>("TimeChunkId")
                        .HasColumnType("int");

                    b.HasKey("SubscribeRoomId", "TimeChunkId");

                    b.HasIndex("TimeChunkId");

                    b.ToTable("SubscribeRoomTimeChunk");
                });

            modelBuilder.Entity("Zhuchkov_backend.Models.SubscribeRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRoom")
                        .HasColumnType("int");

                    b.Property<string>("IdTelegram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscribeRooms");
                });

            modelBuilder.Entity("Zhuchkov_backend.Models.TimeChunk", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TimeChunks");
                });

            modelBuilder.Entity("Zhuchkov_backend.Models.User", b =>
                {
                    b.Property<string>("IdTelegram")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagTelegram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTelegram");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SubscribeRoomTimeChunk", b =>
                {
                    b.HasOne("Zhuchkov_backend.Models.SubscribeRoom", null)
                        .WithMany()
                        .HasForeignKey("SubscribeRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zhuchkov_backend.Models.TimeChunk", null)
                        .WithMany()
                        .HasForeignKey("TimeChunkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
