// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhuchkov_backend.Data;

#nullable disable

namespace Zhuchkov_backend.Migrations
{
    [DbContext(typeof(Zhuchkov_backendContext))]
    [Migration("20241113110804_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Zhuchkov_backend.Models.User", b =>
                {
                    b.Property<string>("IdTelegram")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdStateTelegram")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagTelegram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTelegram");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
